function wind_tab = readUniformWind(filename, dataLines)
%IMPORTFILE Import data from a text file
%  READUNIFORMWIND = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  READUNIFORMWIND = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  readUniformWind = importfile("/home/jgeisler/Temp/CADynTurb_Suite/CADynTurb/ref_sim/sim_dyn_inflow/impulse_URef-6_uni_wind.wnd", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Mar-2026 18:15:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "WindSpeed", "WindDir", "VertSpeed", "HorizShear", "VertShear", "LinV", "Gust"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
wind_tab = readtable(filename, opts);

end